// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://samjothygejcrgxizdra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbWpvdGh5Z2VqY3JneGl6ZHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTgxMjMsImV4cCI6MjA2NTQ5NDEyM30.l1EEPiLYQIQMooa1Xpld7aTYHtxkDmmYPFCX1NumT4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);